# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WELCOME TO PINEAL
email: muwanga.johnk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  welcome to Pineal... the future of ASTRAL PROJECTION!!!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://edsn.comli.com" # the base hostname & protocol for your site
twitter_username: @johnkm
github_username:  krbtjohn

# Build settings
markdown: kramdown
